"use client";
import {useEffect,useMemo,useState} from "react";
import {clientStatuses,documentOptions} from "@/lib/status";

function money(n:any){return `$${Number(n||0).toLocaleString()}`}
function firstName(name:any){return String(name||"Partner").trim().split(/\s+/)[0]||"Partner"}
function greeting(){const h=new Date().getHours(); if(h<12)return "GOOD MORNING"; if(h<17)return "GOOD AFTERNOON"; return "GOOD EVENING";}
function timeAgo(date:any){const t=new Date(date||Date.now()).getTime(); const diff=Math.max(0,Date.now()-t); const m=Math.floor(diff/60000),h=Math.floor(m/60),d=Math.floor(h/24); if(m<1)return "Just now"; if(m<60)return `${m} min ago`; if(h<24)return `${h} hr${h>1?"s":""} ago`; if(d===1)return "Yesterday"; return `${d} days ago`;}
function isHotLead(l:any){const home=Number(l.home_value||0), cash=Number(l.requested_cash||0), income=Number(l.monthly_income||0); const credit=String(l.credit_score||""); return home>=1000000 || cash>=250000 || income>=15000 || /720|740|760|780|800|excellent|good/i.test(credit);}
function hotReason(l:any){if(Number(l.home_value||0)>=1000000)return "High Value Property"; if(Number(l.requested_cash||0)>=250000)return "Large Funding Request"; if(/720|740|760|780|800|excellent/i.test(String(l.credit_score||"")))return "Strong Credit Profile"; return "Priority Lead";}

export default function LenderPortal(){
  const[leads,setLeads]=useState<any[]>([]),[user,setUser]=useState<any>(null),[selectedId,setSelectedId]=useState(""),[status,setStatus]=useState("Application Being Processed"),[fundedAmount,setFundedAmount]=useState(""),[note,setNote]=useState(""),[error,setError]=useState(""),[docType,setDocType]=useState(documentOptions[0]),[docNote,setDocNote]=useState("");
  async function load(){
    const res=await fetch("/api/lenders/leads");
    if(res.status===401){window.location.href="/lender-login";return;}
    const data=await res.json();
    if(!res.ok){setError(data.error||"Unable to load leads.");return;}
    setLeads(data.leads||[]);setUser(data.user||null);if(!selectedId&&data.leads?.[0])setSelectedId(data.leads[0].id)
  }
  useEffect(()=>{load()},[]);
  const selected=useMemo(()=>leads.find(l=>l.id===selectedId),[leads,selectedId]);
  useEffect(()=>{if(selected){setStatus(selected.status||"Application Being Processed");setFundedAmount(String(selected.funded_amount||""))}},[selectedId,selected]);
  const stats=useMemo(()=>({received:leads.length,funded:leads.filter(l=>l.status==="Funded").length,totalFunded:leads.reduce((s,l)=>s+Number(l.funded_amount||0),0),pending:leads.filter(l=>l.status!=="Funded"&&l.status!=="Declined").length}),[leads]);
  async function update(){
    const res=await fetch("/api/lenders/update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leadId:selectedId,status,fundedAmount:Number(fundedAmount||0),note})});
    const data=await res.json().catch(()=>({}));
    if(!res.ok){alert(data.error||"Could not update lead.");return;}
    setNote("");await load();
  }
  async function requestDocument(){
    if(!selectedId){alert("Select a lead first.");return;}
    const res=await fetch("/api/documents/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leadId:selectedId,documentType:docType,note:docNote})});
    const data=await res.json().catch(()=>({}));
    if(!res.ok){alert(data.error||"Could not request document.");return;}
    setDocNote("");await load();
  }
  async function logout(){await fetch("/api/lenders/logout",{method:"POST"});window.location.href="/lender-login"}
  return <main className="min-h-screen overflow-x-hidden bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div className="font-black"><span className="text-blue-700">HELOC CONNECT</span> Lender Portal</div><button onClick={logout} className="rounded-xl bg-slate-900 px-4 py-2 font-black text-white">Logout</button></div></header><div className="mx-auto w-full max-w-7xl px-5 py-7">
    <section className="rounded-[1.4rem] bg-gradient-to-br from-navy via-[#10213a] to-[#0b1220] p-6 text-white shadow-xl"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black tracking-[.30em] text-amber-300">HELOC CONNECT PARTNER DESK</p><h1 className="mt-2 text-4xl font-black">{greeting()}, {firstName(user?.name).toUpperCase()}!</h1><p className="mt-1 text-xl font-black text-blue-100">{user?.mortgage_companies?.name || "Mortgage Company"}</p><p className="mt-3 max-w-2xl text-blue-100">Your assigned HELOC CONNECT leads are ready. Update status here and the client status portal will update automatically.</p></div><div className="rounded-2xl border border-amber-300/30 bg-white/10 p-4 text-right"><p className="text-xs font-black uppercase tracking-[.22em] text-amber-200">Today</p><p className="mt-1 text-2xl font-black">{stats.received} Leads</p><p className="text-sm text-blue-100">{stats.pending} active • {stats.funded} funded</p></div></div></section>
    {error&&<div className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
    <div className="mt-5 grid gap-4 md:grid-cols-4"><Kpi label="Leads Received" value={stats.received}/><Kpi label="Pending" value={stats.pending}/><Kpi label="Funded Deals" value={stats.funded}/><Kpi label="Total Funded Volume" value={money(stats.totalFunded)}/></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-[1.4rem] border bg-white p-6 shadow"><h2 className="text-2xl font-black">Assigned Leads</h2><select className="mt-4 w-full rounded-xl border p-3" value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.tracking_id} - {lead.first_name} {lead.last_name}{isHotLead(lead)?" 🔥 HOT":""} • {timeAgo(lead.created_at)}</option>)}</select>{selected&&<FullLeadDetails lead={selected}/>}</section>
    <section className="rounded-[1.4rem] border bg-white p-6 shadow"><h2 className="text-2xl font-black">Update Lead</h2>{selected?<><label className="mt-4 block text-xs font-black text-slate-500">Status</label><select className="mt-2 w-full rounded-xl border p-3" value={status} onChange={e=>setStatus(e.target.value)}>{clientStatuses.map(s=><option key={s}>{s}</option>)}</select><label className="mt-4 block text-xs font-black text-slate-500">Funded Amount</label><input className="mt-2 w-full rounded-xl border p-3" value={fundedAmount} onChange={e=>setFundedAmount(e.target.value)} placeholder="Funded amount"/><label className="mt-4 block text-xs font-black text-slate-500">Note</label><textarea className="mt-2 min-h-28 w-full rounded-xl border p-3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add update note"/><button onClick={update} className="mt-4 w-full rounded-xl bg-blue-700 p-4 font-black text-white">Save Update</button><hr className="my-6"/><h3 className="text-xl font-black">Request Client Documents</h3><p className="mt-1 text-sm text-slate-500">Requested documents appear instantly on the client status portal.</p><select className="mt-3 w-full rounded-xl border p-3" value={docType} onChange={e=>setDocType(e.target.value)}>{documentOptions.map(d=><option key={d}>{d}</option>)}</select><input className="mt-3 w-full rounded-xl border p-3" value={docNote} onChange={e=>setDocNote(e.target.value)} placeholder="Optional note for client"/><button onClick={requestDocument} className="mt-3 w-full rounded-xl bg-green-600 p-4 font-black text-white">Send Document Request</button>{selected&&<DocumentList documents={selected.documents||[]}/>}</>:<p className="mt-4 text-slate-500">No assigned leads yet.</p>}</section></div>
    <section className="mt-5 rounded-[1.4rem] border bg-white p-6 shadow"><h2 className="text-2xl font-black">Funding Report</h2><div className="mt-4 overflow-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-100 text-xs font-black uppercase text-slate-500"><tr><th className="p-3">Lead</th><th className="p-3">Status</th><th className="p-3">Goal</th><th className="p-3">Requested</th><th className="p-3">Funded</th><th className="p-3">Created</th><th className="p-3">Age</th><th className="p-3">Priority</th></tr></thead><tbody>{leads.map(l=><tr className="border-b" key={l.id}><td className="p-3 font-bold">{l.tracking_id}<br/>{l.first_name} {l.last_name}</td><td className="p-3">{l.status}</td><td className="p-3">{l.loan_purpose}</td><td className="p-3">{money(l.requested_cash)}</td><td className="p-3 font-black">{money(l.funded_amount)}</td><td className="p-3">{new Date(l.created_at).toLocaleDateString()}</td><td className="p-3 font-bold">{timeAgo(l.created_at)}</td><td className="p-3">{isHotLead(l)?<span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-700">🔥 {hotReason(l)}</span>:<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-500">Standard</span>}</td></tr>)}</tbody></table></div></section>
  </div></main>
}
function Kpi({label,value}:{label:string,value:any}){return <div className="rounded-[1.4rem] border bg-white p-5 shadow"><p className="text-sm font-black text-slate-500">{label}</p><b className="mt-1 block text-2xl">{value}</b></div>}
function Info({label,value}:{label:string,value:any}){return <div className="flex justify-between gap-4 border-b pb-2"><span className="font-bold text-slate-500">{label}</span><b className="text-right">{value || "—"}</b></div>}

function smartDetails(lead:any){const note=(lead?.notes||[]).find((n:any)=>String(n.note||"").includes("Smart calculator details:"));return String(note?.note||"").replace("Smart calculator details:\n","").trim();}
function FullLeadDetails({lead}:{lead:any}){const details=smartDetails(lead);return <div className="mt-5 space-y-4 rounded-2xl bg-slate-50 p-5"><div className="grid gap-2 md:grid-cols-2"><Info label="Name" value={`${lead.first_name||""} ${lead.last_name||""}`}/><Info label="Phone" value={lead.phone}/><Info label="Email" value={lead.email}/><Info label="Property Address" value={lead.property_address}/><Info label="Estimated Home Value" value={money(lead.home_value)}/><Info label="Current Mortgage Balance" value={money(lead.mortgage_balance)}/><Info label="Requested Funding" value={money(lead.requested_cash)}/><Info label="Monthly Income" value={money(lead.monthly_income)}/><Info label="Goal" value={lead.loan_purpose}/><Info label="Credit" value={lead.credit_score}/><Info label="Status" value={lead.status}/><Info label="Funded" value={money(lead.funded_amount)}/><Info label="Lead Age" value={timeAgo(lead.created_at)}/><Info label="Priority" value={isHotLead(lead)?`🔥 ${hotReason(lead)}`:"Standard"}/></div>{details&&<section className="rounded-2xl border bg-white p-4"><h3 className="font-black">Smart Calculator Full Intake Details</h3><pre className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm text-slate-700">{details}</pre></section>}<DocumentList documents={lead.documents||[]}/></div>}
function DocumentList({documents}:{documents:any[]}){return <section className="mt-5 rounded-2xl border bg-slate-50 p-4"><h3 className="font-black">Requested Documents</h3>{!documents?.length?<p className="mt-2 text-sm text-slate-500">No documents requested yet.</p>:<div className="mt-3 space-y-2">{documents.map((d:any)=><div key={d.id} className="flex flex-col justify-between gap-2 rounded-xl border bg-white p-3 md:flex-row md:items-center"><div><b>{d.document_type}</b><p className="text-sm text-slate-500">{d.note||""}</p>{d.file_name&&<p className="text-xs font-bold text-green-700">Uploaded: {d.file_name}</p>}</div><span className={(d.status==="Uploaded"?"bg-green-100 text-green-700":"bg-amber-100 text-amber-700")+" rounded-full px-3 py-2 text-xs font-black"}>{d.status}</span></div>)}</div>}</section>}
